# Generated by Django 5.1.7 on 2025-04-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_cleaningtask_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cleaningtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in-progress", "In Progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
