# Generated by Django 5.1.7 on 2025-07-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_notification_read_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="recipient",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="task",
        ),
        migrations.DeleteModel(
            name="Device",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
