# Generated by Django 5.1.7 on 2025-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_profile_digest_opt_out"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
