# Generated by Django 5.1.7 on 2025-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_device_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="push_sent",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
