# Generated by Django 5.1.7 on 2025-08-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_notification_verb"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                    ("owner", "Owner"),
                ],
                default="staff",
                help_text="App role separate from Django is_staff/is_superuser.",
                max_length=16,
            ),
        ),
    ]
