# Generated by Django 5.1.7 on 2025-08-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_recurring_schedules_and_booking_import"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("manager", "Manager"),
                    ("owner", "Superuser"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn/Pool"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                help_text="App role separate from Django is_staff/is_superuser.",
                max_length=16,
            ),
        ),
    ]
