# Generated by Django 5.1.7 on 2025-08-30 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_staff_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America/New_York", "Eastern Time (Tampa, FL)"),
                    ("America/Los_Angeles", "Pacific Time (San Jose, CA)"),
                    ("America/Chicago", "Central Time (Chicago, IL)"),
                    ("America/Denver", "Mountain Time (Denver, CO)"),
                    ("America/Phoenix", "Arizona Time (Phoenix, AZ)"),
                    ("America/Anchorage", "Alaska Time (Anchorage, AK)"),
                    ("Pacific/Honolulu", "Hawaii Time (Honolulu, HI)"),
                    ("Asia/Ho_Chi_Minh", "Vietnam Time (Ho Chi Minh City)"),
                    ("Europe/London", "GMT/BST (London, UK)"),
                    ("UTC", "UTC (Coordinated Universal Time)"),
                ],
                default="America/New_York",
                help_text="Your local timezone for displaying dates and times",
                max_length=32,
            ),
        ),
    ]
