# Generated by Django 5.1.7 on 2025-08-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_update_timezone_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.TextField(
                blank=True, help_text="User's address (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="User's phone number (optional)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff/Crew"),
                    ("manager", "Manager"),
                    ("superuser", "Superuser"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                help_text="App role separate from Django is_staff/is_superuser.",
                max_length=16,
            ),
        ),
    ]
