# Generated by Django 5.1.7 on 2025-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_profile_address_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of adult guests"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="booked_on",
            field=models.DateTimeField(
                blank=True, help_text="When the booking was made", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_in_time",
            field=models.TimeField(
                blank=True, help_text="Check-in time (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_time",
            field=models.TimeField(
                blank=True, help_text="Check-out time (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="children",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of children"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="early_checkin_requested",
            field=models.BooleanField(
                default=False, help_text="Early check-in requested"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="earnings_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Earnings from this booking",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="earnings_currency",
            field=models.CharField(
                default="USD", help_text="Currency for earnings", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="external_code",
            field=models.CharField(
                blank=True,
                help_text="Confirmation code from booking platform",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="external_status",
            field=models.CharField(
                blank=True, help_text="Status from external platform", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="heat_requested",
            field=models.BooleanField(default=False, help_text="Pool heat requested"),
        ),
        migrations.AddField(
            model_name="booking",
            name="import_source",
            field=models.CharField(
                blank=True,
                help_text="Source of this import (Excel, API, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="infants",
            field=models.PositiveIntegerField(default=0, help_text="Number of infants"),
        ),
        migrations.AddField(
            model_name="booking",
            name="listing_name",
            field=models.CharField(
                blank=True, help_text="Listing name from platform", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="nights",
            field=models.PositiveIntegerField(
                blank=True, help_text="Number of nights", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="pnp_requested",
            field=models.BooleanField(
                default=False, help_text="Pack 'n Play requested"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="property_label_raw",
            field=models.CharField(
                blank=True,
                help_text="Original property text from import",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="raw_row_data",
            field=models.JSONField(
                blank=True, help_text="Original Excel row data for audit", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="same_day_flag",
            field=models.BooleanField(
                default=False, help_text="Same-day turnover flag"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="same_day_note",
            field=models.TextField(
                blank=True, help_text="Notes about same-day turnover"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Booking source (Airbnb, VRBO, Direct, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_contact",
            field=models.CharField(
                blank=True,
                help_text="Phone, email, or other contact info",
                max_length=200,
            ),
        ),
    ]
