# Generated by Django 5.1.7 on 2025-08-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_remove_booking_api_booking_externa_7b71f1_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("booked", "Booked"),
                    ("confirmed", "Confirmed"),
                    ("currently_hosting", "Currently Hosting"),
                    ("owner_staying", "Owner Staying"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="booked",
                max_length=20,
            ),
        ),
    ]
