# Generated by Django 5.1.7 on 2025-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="history",
            field=models.TextField(
                blank=True, default="[]", help_text="JSON array of change history"
            ),
        ),
    ]
