# Generated by Django 5.1.7 on 2025-08-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_inventoryitem_history_property_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytransaction",
            name="history",
            field=models.TextField(
                blank=True, default="[]", help_text="JSON array of change history"
            ),
        ),
    ]
