# Generated by Django 5.1.7 on 2025-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_add_skipped_rows_to_import_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingimportlog",
            name="early_return_rows",
            field=models.IntegerField(
                default=0, help_text="Number of rows that returned early (need review)"
            ),
        ),
    ]
