# Generated by Django 5.1.7 on 2025-08-31 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_add_import_conflict_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingimportlog",
            options={
                "ordering": ["-imported_at"],
                "verbose_name": "Booking Import Log",
                "verbose_name_plural": "Booking Import Logs",
            },
        ),
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="early_return_rows",
        ),
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="skipped_rows",
        ),
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="warnings_count",
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="errors_count",
            field=models.IntegerField(
                default=0, help_text="Number of rows with errors"
            ),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="errors_log",
            field=models.TextField(blank=True, help_text="Detailed error log"),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="successful_imports",
            field=models.IntegerField(
                default=0, help_text="Number of successful imports"
            ),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="total_rows",
            field=models.IntegerField(default=0, help_text="Total rows in Excel file"),
        ),
        migrations.CreateModel(
            name="ConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution_data",
                    models.JSONField(help_text="User's resolution decisions"),
                ),
                (
                    "results",
                    models.JSONField(help_text="Results of applying resolutions"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflict Resolution",
                "verbose_name_plural": "Conflict Resolutions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="ImportConflict",
        ),
    ]
