# Generated by Django 5.1.7 on 2025-09-01 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_remove_bookingconflictsession_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("view_properties", "View Properties"),
                            ("add_properties", "Add Properties"),
                            ("change_properties", "Edit Properties"),
                            ("delete_properties", "Delete Properties"),
                            ("view_bookings", "View Bookings"),
                            ("add_bookings", "Add Bookings"),
                            ("change_bookings", "Edit Bookings"),
                            ("delete_bookings", "Delete Bookings"),
                            ("import_bookings", "Import Bookings from Excel"),
                            ("view_tasks", "View Tasks"),
                            ("add_tasks", "Add Tasks"),
                            ("change_tasks", "Edit Tasks"),
                            ("delete_tasks", "Delete Tasks"),
                            ("assign_tasks", "Assign Tasks to Others"),
                            ("view_all_tasks", "View All Tasks (not just own)"),
                            ("view_users", "View Users"),
                            ("add_users", "Add Users"),
                            ("change_users", "Edit Users"),
                            ("delete_users", "Delete Users"),
                            ("manage_user_permissions", "Manage User Permissions"),
                            ("view_reports", "View Reports"),
                            ("export_data", "Export Data"),
                            ("view_analytics", "View Analytics Dashboard"),
                            ("access_admin_panel", "Access Admin Panel"),
                            ("manage_system_settings", "Manage System Settings"),
                            ("view_system_logs", "View System Logs"),
                            ("manage_notifications", "Manage Notifications"),
                            ("view_checklists", "View Checklists"),
                            ("add_checklists", "Add Checklists"),
                            ("change_checklists", "Edit Checklists"),
                            ("delete_checklists", "Delete Checklists"),
                            ("view_devices", "View Devices"),
                            ("add_devices", "Add Devices"),
                            ("change_devices", "Edit Devices"),
                            ("delete_devices", "Delete Devices"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what this permission allows",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this permission is currently available",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Custom Permission",
                "verbose_name_plural": "Custom Permissions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Staff/Crew"),
                            ("manager", "Manager"),
                            ("superuser", "Superuser"),
                            ("viewer", "Viewer"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this permission is granted to this role",
                    ),
                ),
                (
                    "can_delegate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether users with this role can grant/revoke this permission to others",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.custompermission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission",
                "verbose_name_plural": "Role Permissions",
                "ordering": ["role", "permission__name"],
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.CreateModel(
            name="UserPermissionOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "granted",
                    models.BooleanField(
                        help_text="Whether this permission is granted (True) or explicitly denied (False)"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for this permission override"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this override expires (optional)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.custompermission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Permission Override",
                "verbose_name_plural": "User Permission Overrides",
                "ordering": ["user__username", "permission__name"],
                "unique_together": {("user", "permission")},
            },
        ),
    ]
