# Generated by Django 5.1.7 on 2025-09-01 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_custompermission_rolepermission_and_more"),
    ]

    operations = []
