# Generated by Django 5.1.7 on 2025-09-02 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_auto_20250901_0239"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskimage",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_task_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="custompermission",
            name="name",
            field=models.CharField(
                choices=[
                    ("view_properties", "View Properties"),
                    ("add_properties", "Add Properties"),
                    ("change_properties", "Edit Properties"),
                    ("delete_properties", "Delete Properties"),
                    ("view_bookings", "View Bookings"),
                    ("add_bookings", "Add Bookings"),
                    ("change_bookings", "Edit Bookings"),
                    ("delete_bookings", "Delete Bookings"),
                    ("import_bookings", "Import Bookings from Excel"),
                    ("view_tasks", "View Tasks"),
                    ("add_tasks", "Add Tasks"),
                    ("change_tasks", "Edit Tasks"),
                    ("delete_tasks", "Delete Tasks"),
                    ("assign_tasks", "Assign Tasks to Others"),
                    ("view_all_tasks", "View All Tasks (not just own)"),
                    ("view_users", "View Users"),
                    ("add_users", "Add Users"),
                    ("change_users", "Edit Users"),
                    ("delete_users", "Delete Users"),
                    ("manage_user_permissions", "Manage User Permissions"),
                    ("view_reports", "View Reports"),
                    ("export_data", "Export Data"),
                    ("view_analytics", "View Analytics Dashboard"),
                    ("access_admin_panel", "Access Admin Panel"),
                    ("manager_portal_access", "Manager Portal Access"),
                    ("manage_system_settings", "Manage System Settings"),
                    ("view_system_logs", "View System Logs"),
                    ("manage_notifications", "Manage Notifications"),
                    ("manage_files", "Manage Files"),
                    ("manage_permissions", "Manage Permissions"),
                    ("system_metrics_access", "System Metrics Access"),
                    ("system_recovery_access", "System Crash Recovery Access"),
                    ("manage_bookings", "Manage Booking Operations"),
                    ("view_checklists", "View Checklists"),
                    ("add_checklists", "Add Checklists"),
                    ("change_checklists", "Edit Checklists"),
                    ("delete_checklists", "Delete Checklists"),
                    ("view_devices", "View Devices"),
                    ("add_devices", "Add Devices"),
                    ("change_devices", "Edit Devices"),
                    ("delete_devices", "Delete Devices"),
                    ("view_inventory", "View Inventory"),
                    ("change_inventory", "Edit Inventory"),
                    ("manage_inventory", "Manage Inventory"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
