# Generated by Django 5.1.7 on 2025-09-04 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_booking_created_by_booking_created_via_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        help_text="Model name of the object being audited",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="Primary key of the object being audited",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="Type of action performed",
                        max_length=10,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text="JSONB diff of changes made (before/after values)",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique request identifier",
                        max_length=100,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of the request", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent string from the request"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the audit event was recorded"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Event",
                "verbose_name_plural": "Audit Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="api_auditev_object__98f7b1_idx",
                    ),
                    models.Index(
                        fields=["action"], name="api_auditev_action_df2975_idx"
                    ),
                    models.Index(
                        fields=["actor"], name="api_auditev_actor_i_ac4354_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="api_auditev_created_e094d4_idx"
                    ),
                ],
            },
        ),
    ]
