# Generated by Django 5.1.7 on 2025-09-05 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_booking_deleted_at_booking_deleted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="booking",
            name="uniq_booking_external_code_per_property_source",
        ),
        migrations.RemoveConstraint(
            model_name="property",
            name="uniq_property_name",
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_code__gt", ""), ("is_deleted", False)),
                fields=("property", "source", "external_code"),
                name="uniq_booking_external_code_per_property_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="uniq_property_name",
            ),
        ),
    ]
