# Generated by Django 5.1.7 on 2025-09-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_update_constraints_for_soft_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autotasktemplate",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn/Pool"),
                    ("inspection", "Inspection"),
                    ("preparation", "Preparation"),
                    ("other", "Other"),
                ],
                default="cleaning",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="checklisttemplate",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn/Pool"),
                    ("inspection", "Inspection"),
                    ("preparation", "Preparation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn/Pool"),
                    ("inspection", "Inspection"),
                    ("preparation", "Preparation"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("administration", "Administration"),
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn/Pool"),
                    ("inspection", "Inspection"),
                    ("preparation", "Preparation"),
                    ("other", "Other"),
                ],
                default="cleaning",
                max_length=20,
            ),
        ),
    ]
