# Generated by Django 5.1.10 on 2025-09-06 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_add_idempotent_task_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_attempt", "Login Attempt"),
                            ("login_success", "Login Success"),
                            ("login_failure", "Login Failure"),
                            ("token_issued", "Token Issued"),
                            ("token_refreshed", "Token Refreshed"),
                            ("token_revoked", "Token Revoked"),
                            ("password_reset", "Password Reset"),
                            ("suspicious_activity", "Suspicious Activity"),
                            ("rate_limit_exceeded", "Rate Limit Exceeded"),
                            ("permission_denied", "Permission Denied"),
                            ("account_locked", "Account Locked"),
                            ("session_expired", "Session Expired"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "security_events",
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="security_ev_event_t_0dd22d_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="security_ev_user_id_70c595_idx",
                    ),
                    models.Index(
                        fields=["severity", "resolved"],
                        name="security_ev_severit_23d5a6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="security_ev_ip_addr_b3ff8b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SuspiciousActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("activity_type", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=1)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("blocked", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "suspicious_activity",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "blocked"],
                        name="suspicious__ip_addr_bfc10e_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "count"],
                        name="suspicious__activit_f00dfb_idx",
                    ),
                ],
                "unique_together": {("ip_address", "activity_type")},
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("device_type", models.CharField(default="unknown", max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("jwt_jti", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_sessio_user_id_bb1b83_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="user_sessio_session_cc84b9_idx"
                    ),
                    models.Index(
                        fields=["jwt_jti"], name="user_sessio_jwt_jti_7513c1_idx"
                    ),
                ],
            },
        ),
    ]
