# Generated by Django 5.1.10 on 2025-09-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_securityevent_suspiciousactivity_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskimage",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, help_text="Image height in pixels", null=True
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="original_size_bytes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Original upload size before optimization",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="size_bytes",
            field=models.PositiveIntegerField(
                blank=True, help_text="Optimized file size in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="width",
            field=models.PositiveIntegerField(
                blank=True, help_text="Image width in pixels", null=True
            ),
        ),
    ]
