# Generated by Django 5.1.10 on 2025-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_add_team_visibility_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostfounditem",
            name="history",
            field=models.TextField(
                blank=True, help_text="JSON field tracking changes to this item"
            ),
        ),
    ]
