# Generated by Django 5.1.10 on 2025-09-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_add_lost_found_history"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS btree_gist;",
            reverse_sql="DROP EXTENSION IF EXISTS btree_gist;",
        ),
    ]


