# Generated by Django 5.1.10 on 2025-09-09 08:20

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


def add_booking_overlap_constraint(apps, schema_editor):
    """Add booking overlap constraint only for PostgreSQL databases."""
    if connection.vendor == 'postgresql':
        try:
            # Ensure btree_gist extension is available
            schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
        except Exception as e:
            print(f"Warning: Could not create btree_gist extension: {e}")
            return

        # Drop if exists to ensure idempotency
        try:
            schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")
        except Exception:
            pass

        # Create the constraint using raw SQL for PostgreSQL
        try:
            schema_editor.execute(
                """
                ALTER TABLE api_booking 
                ADD CONSTRAINT booking_no_overlap_active 
                EXCLUDE USING gist (
                    property_id gist_int8_ops WITH =,
                    tstzrange(check_in_date, check_out_date) WITH &&
                ) WHERE (status NOT IN ('cancelled', 'completed'));
                """
            )
        except Exception as e:
            print(f"Warning: Could not create booking overlap constraint: {e}")
            pass


def remove_booking_overlap_constraint(apps, schema_editor):
    """Remove booking overlap constraint only for PostgreSQL databases."""
    if connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_btree_gist_extension"),
        ("api", "0062_lostfound_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_booking_overlap_constraint,
            reverse_code=remove_booking_overlap_constraint,
        ),
    ]
