# Generated by Django 5.1.10 on 2025-09-09 08:20

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


def add_booking_overlap_constraint(apps, schema_editor):
    """Add booking overlap constraint only for PostgreSQL databases."""
    if connection.vendor == 'postgresql':
        # Drop if exists to ensure idempotency
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")
        # Create the constraint using raw SQL for PostgreSQL
        schema_editor.execute(
            """
            ALTER TABLE api_booking 
            ADD CONSTRAINT booking_no_overlap_active 
            EXCLUDE USING gist (
                property_id WITH =,
                tstzrange(check_in_date, check_out_date) WITH &&
            ) WHERE (status NOT IN ('cancelled', 'completed'));
            """
        )


def remove_booking_overlap_constraint(apps, schema_editor):
    """Remove booking overlap constraint only for PostgreSQL databases."""
    if connection.vendor == 'postgresql':
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_btree_gist_extension"),
        ("api", "0062_lostfound_provenance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_booking_overlap_constraint,
            reverse_code=remove_booking_overlap_constraint,
        ),
    ]
