# Generated by Django 5.1.10 on 2025-09-10 03:25

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


def add_booking_no_overlap_constraint(apps, schema_editor):
    if connection.vendor == 'postgresql':
        Booking = apps.get_model('api', 'Booking')
        # Drop existing constraint if present to avoid duplicate errors
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")
        constraint = django.contrib.postgres.constraints.ExclusionConstraint(
            condition=models.Q(
                ("status__in", ["cancelled", "completed"]), _negated=True
            ),
            expressions=[
                (models.F("property"), "="),
                (
                    models.Func(
                        models.F("check_in_date"),
                        models.F("check_out_date"),
                        function="tstzrange",
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                    "&&",
                ),
            ],
            name="booking_no_overlap_active",
        )
        # Add the constraint directly
        schema_editor.add_constraint(Booking, constraint)


def remove_booking_no_overlap_constraint(apps, schema_editor):
    if connection.vendor == 'postgresql':
        # Remove the constraint directly (safe if already absent)
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_add_task_group_to_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            add_booking_no_overlap_constraint,
            reverse_code=remove_booking_no_overlap_constraint,
        ),
    ]
