# Generated by Django 5.1.12 on 2025-09-11 18:26

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


def ensure_booking_overlap_constraint(apps, schema_editor):
    """
    Ensure the booking_no_overlap_active exclusion constraint exists exactly once.
    Idempotent and Postgres-only to avoid CI failures when re-applied.
    """
    if connection.vendor != 'postgresql':
        return

    try:
        # Ensure btree_gist extension is available
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    except Exception as e:
        # If extension creation fails, skip constraint creation
        print(f"Warning: Could not create btree_gist extension: {e}")
        return

    # Drop if exists (covers prior raw-SQL migration 0063 or partial runs)
    try:
        schema_editor.execute(
            "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
        )
    except Exception:
        pass  # Ignore if constraint doesn't exist

    # Recreate using raw SQL to avoid relation/index name collisions
    try:
        schema_editor.execute(
            """
            ALTER TABLE api_booking 
            ADD CONSTRAINT booking_no_overlap_active 
            EXCLUDE USING gist (
                property_id gist_int8_ops WITH =,
                tstzrange(check_in_date, check_out_date) WITH &&
            ) WHERE (status NOT IN ('cancelled', 'completed'));
            """
        )
    except Exception as e:
        # If constraint creation fails, log and continue
        print(f"Warning: Could not create booking overlap constraint: {e}")
        pass


def drop_booking_overlap_constraint(apps, schema_editor):
    if connection.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0068_add_before_after_photo_fields_only"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            ensure_booking_overlap_constraint,
            reverse_code=drop_booking_overlap_constraint,
        ),
    ]
