# Generated by Django 5.1.12 on 2025-09-12 19:53

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_invitecode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff/Crew"),
                    ("manager", "Manager"),
                    ("superuser", "Superuser"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # No-op for SQLite
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
