# Generated by Django 5.1.12 on 2025-09-12 19:53

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_invitecode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitecode",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff/Crew"),
                    ("manager", "Manager"),
                    ("superuser", "Superuser"),
                    ("viewer", "Viewer"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint 
                    WHERE conname = 'booking_no_overlap_active'
                ) THEN
                    ALTER TABLE api_booking ADD CONSTRAINT booking_no_overlap_active
                    EXCLUDE USING gist (
                        property_id WITH =,
                        tstzrange(check_in_date, check_out_date) WITH &&
                    ) WHERE (status NOT IN ('cancelled', 'completed'));
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;
            """,
        ),
    ]
