# Generated by Django 5.1.12 on 2025-09-15 18:15

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_update_invite_code_role_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="booking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(
                    ("status__in", ["cancelled", "completed"]), _negated=True
                ),
                expressions=[
                    (models.F("property"), "="),
                    (
                        models.Func(
                            models.F("check_in_date"),
                            models.F("check_out_date"),
                            function="tstzrange",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                ],
                name="booking_no_overlap_active",
            ),
        ),
    ]
