# Generated by Django 5.1.12 on 2025-09-15 18:15

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_update_invite_code_role_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # No-op for SQLite
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
