# Generated by Django 5.1.12 on 2025-09-16 00:42

from django.db import migrations, connection


def fix_booking_overlap_constraint(apps, schema_editor):
    """
    Fix the booking overlap constraint syntax for PostgreSQL.
    Drop the existing constraint and recreate it with correct syntax.
    """
    if connection.vendor != 'postgresql':
        return

    try:
        # Ensure btree_gist extension is available
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    except Exception as e:
        print(f"Warning: Could not create btree_gist extension: {e}")
        return

    # Drop existing constraint if it exists
    try:
        schema_editor.execute(
            "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
        )
    except Exception as e:
        print(f"Warning: Could not drop existing constraint: {e}")

    # Create the constraint with correct syntax
    try:
        schema_editor.execute(
            """
            ALTER TABLE api_booking 
            ADD CONSTRAINT booking_no_overlap_active 
            EXCLUDE USING gist (
                property_id gist_int8_ops WITH =,
                tstzrange(check_in_date, check_out_date) WITH &&
            ) WHERE (status NOT IN ('cancelled', 'completed'));
            """
        )
        print("Successfully created booking overlap constraint")
    except Exception as e:
        print(f"Warning: Could not create booking overlap constraint: {e}")


def reverse_fix_booking_overlap_constraint(apps, schema_editor):
    """Remove the booking overlap constraint."""
    if connection.vendor == 'postgresql':
        try:
            schema_editor.execute(
                "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
            )
        except Exception as e:
            print(f"Warning: Could not drop constraint: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_fix_ci_postgresql_compatibility"),
    ]

    operations = [
        migrations.RunPython(
            fix_booking_overlap_constraint,
            reverse_code=reverse_fix_booking_overlap_constraint,
        ),
    ]
