# Generated by Django 5.1.12 on 2025-09-19 07:45

from django.db import migrations, connection


def ensure_booking_overlap_constraint(apps, schema_editor):
    """Create booking_no_overlap_active exclusion constraint if missing (idempotent)."""
    if connection.vendor != 'postgresql':
        return

    # Ensure extension is present (safe if already installed)
    try:
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
    except Exception:
        pass

    # Check if constraint already exists
    exists_sql = (
        "SELECT 1 FROM pg_constraint c "
        "JOIN pg_class t ON c.conrelid = t.oid "
        "WHERE c.conname = 'booking_no_overlap_active' AND t.relname = 'api_booking';"
    )
    with connection.cursor() as cursor:
        cursor.execute(exists_sql)
        exists = cursor.fetchone() is not None

    if exists:
        return

    # Create the constraint with correct syntax
    schema_editor.execute(
        """
        ALTER TABLE api_booking 
        ADD CONSTRAINT booking_no_overlap_active 
        EXCLUDE USING gist (
            property_id gist_int8_ops WITH =,
            tstzrange(check_in_date, check_out_date) WITH &&
        ) WHERE (status NOT IN ('cancelled', 'completed'));
        """
    )


def drop_booking_overlap_constraint(apps, schema_editor):
    if connection.vendor != 'postgresql':
        return
    schema_editor.execute(
        "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_fix_booking_overlap_constraint_syntax"),
    ]

    operations = [
        migrations.RunPython(
            ensure_booking_overlap_constraint,
            reverse_code=drop_booking_overlap_constraint,
        ),
    ]
