# Generated by Django 5.1.12 on 2025-09-23 20:35

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_unify_checklist_photos_into_taskimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="taskimage",
            name="checklist_response",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_images",
                to="api.checklistresponse",
            ),
        ),
        migrations.AlterField(
            model_name="taskimage",
            name="photo_type",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("after", "After"),
                    ("during", "During"),
                    ("reference", "Reference"),
                    ("damage", "Damage"),
                    ("general", "General"),
                    ("checklist", "Checklist"),
                ],
                default="general",
                help_text="Type of photo for before/after comparison",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="taskimage",
            index=models.Index(
                fields=["checklist_response"], name="api_taskima_checkli_dcd86f_idx"
            ),
        ),
        # Note: Exclusion constraint 'booking_no_overlap_active' already exists in DB; do not re-add here
    ]
