"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import socket
from pathlib import Path
import os

# Production logging configuration
from backend.logging_config import setup_logging



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*g+qjl3q3q8h1tnkws9(sd^tm(t!ld8rtdre6r5yc+d=jw_yn!"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

def get_local_ip():
    try:
        # This creates a temporary connection to determine your IP address
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
    except Exception:
        ip = '127.0.0.1'
    finally:
        s.close()
    return ip

ALLOWED_HOSTS = ['localhost', '127.0.0.1', get_local_ip()]

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",
    "api.apps.ApiConfig",
    "django_filters",
    "django_crontab",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # Django's auth middleware must run before you try to use request.user
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Admin access control middleware (must run after authentication)
    "backend.middleware.AdminAccessMiddleware",
    # Now your timezone middleware can safely reference request.user
    "backend.middleware.TimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Production logging and monitoring middleware
    "backend.middleware.RequestLoggingMiddleware",
    "backend.middleware.ErrorLoggingMiddleware", 
    "backend.middleware.SecurityHeadersMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'api' / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# Add your REST framework configuration here:
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"  # System default: Tampa, FL (Eastern Time)

# AriStay Timezone Configuration
ARISTAY_DEFAULT_TIMEZONE = "America/New_York"  # Tampa, FL
ARISTAY_TIMEZONE_DISPLAY_NAME = "Tampa, FL"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [ BASE_DIR / 'static' ]    # so project-level static/ is on the path

# === Add these for media uploads ===
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# email address that will appear in the From: header of all outgoing mail
DEFAULT_FROM_EMAIL = "no-reply@aristay-internal.com"

# the URL your users will click through to finish activation/reset
# (point this at your front-end, e.g. localhost:3000)
FRONTEND_URL = "http://localhost:3000"

# during development, just dump emails to the console instead of real SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mailersend.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'MS_T2FlZ8@aristay-internal.cloud'
EMAIL_HOST_PASSWORD = 'mssp.Yun5OWw.v69oxl53kzkg785k.9UyPJrd'

DEFAULT_FROM_EMAIL = 'noreply@aristay-internal.cloud'

FCM_SERVER_KEY = "your-firebase-server-key-here"
FIREBASE_PROJECT_ID = 'aristayapp'
FIREBASE_CREDENTIALS_FILE = BASE_DIR / 'firebase_credentials.json'

# --- Email digest feature flag ---------------------------------
# Default: OFF.  Turn ON with   export EMAIL_DIGEST_ENABLED=true
EMAIL_DIGEST_ENABLED = os.getenv("EMAIL_DIGEST_ENABLED", "false").lower() == "true"

# Run the digest at this UTC hour (0-23).  Overridable per env.
EMAIL_DIGEST_HOUR_UTC = int(os.getenv("EMAIL_DIGEST_HOUR_UTC", "12"))

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

CRONJOBS = [
    (
        f"0 {EMAIL_DIGEST_HOUR_UTC} * * *",
        "django.core.management.call_command",
        ["send_digest"],
        {"stdout": str(LOG_DIR / "digest.log"),
         "stderr": str(LOG_DIR / "digest_err.log")},
    ),
]

CRONTAB_DJANGO_SETTINGS = "backend.settings"

# ============================================================================
# PRODUCTION LOGGING & MONITORING CONFIGURATION
# ============================================================================

# Environment configuration
ENVIRONMENT = os.getenv('DJANGO_ENVIRONMENT', 'development')
VERSION = os.getenv('APP_VERSION', '1.0.0')

# Sentry configuration for error tracking
SENTRY_DSN = os.getenv('SENTRY_DSN', None)

# Performance monitoring thresholds
SLOW_REQUEST_THRESHOLD = int(os.getenv('SLOW_REQUEST_THRESHOLD', '1000'))  # milliseconds
SLOW_QUERY_THRESHOLD = int(os.getenv('SLOW_QUERY_THRESHOLD', '100'))      # milliseconds

# Initialize logging system
setup_logging(debug=DEBUG, sentry_dsn=SENTRY_DSN)

# Sentry configuration (if DSN is provided)
if SENTRY_DSN:
    from backend.sentry_config import setup_sentry
    setup_sentry(
        dsn=SENTRY_DSN,
        environment=ENVIRONMENT,
        debug=DEBUG,
        sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1'))
    )

# Security settings for production
if not DEBUG:
    # HTTPS settings
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Security headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Cookie security
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    
    # Tighten CORS for production
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        origin.strip() 
        for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') 
        if origin.strip()
    ]
    
    # Database connection pooling for production
    DATABASES['default']['CONN_MAX_AGE'] = 60
    DATABASES['default']['OPTIONS'] = {
        'MAX_CONNS': int(os.getenv('DB_MAX_CONNECTIONS', '20')),
    }

# Logging-specific settings
LOGGING_CONFIG = None  # Disable Django's default logging config

# Email settings for admin notifications
if not DEBUG:
    ADMINS = [
        (name.strip(), email.strip()) 
        for admin in os.getenv('DJANGO_ADMINS', '').split(',')
        if admin.strip() and '@' in admin
        for name, email in [admin.strip().split(':')]
    ]
    
    MANAGERS = ADMINS
    
    # Email backend for error notifications
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'aristay@example.com')
    SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Cache configuration for production
if not DEBUG:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': int(os.getenv('REDIS_MAX_CONNECTIONS', '50')),
                    'retry_on_timeout': True,
                },
            },
            'TIMEOUT': int(os.getenv('CACHE_TIMEOUT', '300')),  # 5 minutes default
        }
    }

# Rate limiting settings
RATELIMIT_ENABLE = not DEBUG
RATELIMIT_USE_CACHE = 'default'

# ============================================================================
# UNIFIED LOGIN CONFIGURATION
# ============================================================================

# Redirect users to unified login/logout
LOGIN_URL = '/login/'
LOGOUT_REDIRECT_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/'  # Will be overridden by our custom logic