# Generated by Django 5.1.7 on 2025-07-16 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_device_notification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterField(
            model_name="notification",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="api.task",
            ),
        ),
    ]
