# Generated by Django 5.1.7 on 2025-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_notification_recipient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                blank=True, help_text="Optional deadline for task (UTC)", null=True
            ),
        ),
    ]
