# Generated by Django 5.1.7 on 2025-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_device_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="digest_opt_out",
            field=models.BooleanField(default=False),
        ),
    ]
