# Generated by Django 5.1.7 on 2025-08-11 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_notification_push_sent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="muted_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users that muted notifications for this task",
                related_name="muted_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
