# Generated by Django 5.1.7 on 2025-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_task_muted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("status_changed", "Status changed"),
                    ("due_date_changed", "Due date changed"),
                    ("title_changed", "Title changed"),
                    ("description_changed", "Description changed"),
                    ("photo_added", "Photo added"),
                    ("photo_deleted", "Photo deleted"),
                    ("created", "Task created"),
                ],
                default="status_changed",
                max_length=32,
            ),
        ),
    ]
