# Generated by Django 5.1.7 on 2025-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_mvp_phase1_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="sku",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
