# Generated by Django 5.1.7 on 2025-08-28 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_fix_inventory_sku"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingImportTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV File"),
                            ("ical", "iCal/Calendar"),
                            ("airbnb", "Airbnb Export"),
                            ("vrbo", "VRBO Export"),
                            ("api", "API Integration"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "date_format",
                    models.CharField(
                        default="%Y-%m-%d",
                        help_text="Python strftime format",
                        max_length=50,
                    ),
                ),
                (
                    "checkin_field",
                    models.CharField(
                        default="check_in",
                        help_text="CSV column name for check-in",
                        max_length=100,
                    ),
                ),
                (
                    "checkout_field",
                    models.CharField(
                        default="check_out",
                        help_text="CSV column name for check-out",
                        max_length=100,
                    ),
                ),
                (
                    "guest_name_field",
                    models.CharField(
                        default="guest_name",
                        help_text="CSV column for guest name",
                        max_length=100,
                    ),
                ),
                (
                    "guest_contact_field",
                    models.CharField(
                        default="guest_email",
                        help_text="CSV column for contact",
                        max_length=100,
                    ),
                ),
                ("auto_create_tasks", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_import", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_templates",
                        to="api.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookingImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "import_file",
                    models.FileField(
                        blank=True, null=True, upload_to="booking_imports/%Y/%m/"
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("successful_imports", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("errors_log", models.TextField(blank=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_logs",
                        to="api.bookingimporttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("administration", "Administration"),
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("laundry", "Laundry"),
                            ("lawn_pool", "Lawn/Pool"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "task_title_template",
                    models.CharField(
                        help_text="Use {date}, {property} for dynamic values",
                        max_length=200,
                    ),
                ),
                (
                    "task_description_template",
                    models.TextField(
                        blank=True, help_text="Template for task description"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.IntegerField(
                        default=1, help_text="Every X days/weeks/months"
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="For weekly schedules",
                        null=True,
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True, help_text="For monthly schedules (1-31)", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When to start generating tasks"),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="When to stop (optional)", null=True
                    ),
                ),
                (
                    "time_of_day",
                    models.TimeField(
                        default="09:00:00", help_text="Default time for generated tasks"
                    ),
                ),
                (
                    "advance_days",
                    models.IntegerField(
                        default=1, help_text="Create task X days in advance"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_generated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time tasks were generated",
                        null=True,
                    ),
                ),
                (
                    "checklist_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.checklisttemplate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_templates",
                        to="api.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property_ref", "task_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="bookingimporttemplate",
            name="cleaning_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="Schedule to trigger for cleaning tasks",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cleaning_imports",
                to="api.scheduletemplate",
            ),
        ),
        migrations.CreateModel(
            name="GeneratedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_for_date",
                    models.DateField(help_text="The date this task was scheduled for"),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_from",
                        to="api.task",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_tasks",
                        to="api.scheduletemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_for_date"],
                "unique_together": {("schedule", "generated_for_date")},
            },
        ),
    ]
