# Generated by Django 5.1.7 on 2025-08-30 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_enhance_booking_model_for_excel_import"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={
                ("property", "check_in_date", "check_out_date", "guest_name")
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="imported_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this booking was first imported",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="last_import_update",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="When this booking was last updated via import",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="raw_row",
            field=models.JSONField(
                blank=True, default=dict, help_text="Original Excel row data for audit"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(default=1, help_text="Number of adults"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in_time",
            field=models.TimeField(blank=True, help_text="Check-in time", null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_time",
            field=models.TimeField(blank=True, help_text="Check-out time", null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="earnings_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Earnings amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="earnings_currency",
            field=models.CharField(
                default="USD", help_text="Earnings currency", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="external_code",
            field=models.CharField(
                blank=True,
                help_text="Confirmation code from external platform",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="guest_contact",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="booking",
            name="listing_name",
            field=models.CharField(
                blank=True,
                help_text="Listing name from external platform",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="property_label_raw",
            field=models.CharField(
                blank=True,
                help_text="Original property text from import file",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="same_day_flag",
            field=models.BooleanField(
                default=False, help_text="Flag for same day check-in/out"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="same_day_note",
            field=models.TextField(blank=True, help_text="Same day check-in/out notes"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Booking source (Airbnb, VRBO, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["external_code", "source"],
                name="api_booking_externa_7b71f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_date", "check_out_date"],
                name="api_booking_check_i_5302b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["source", "external_status"],
                name="api_booking_source_856f40_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="booked_on",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="early_checkin_requested",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="heat_requested",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="import_source",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="pnp_requested",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="raw_row_data",
        ),
    ]
