# Generated by Django 5.1.7 on 2025-08-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_booking_unique_together_booking_imported_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingimportlog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_logs",
                to="api.bookingimporttemplate",
            ),
        ),
    ]
