# Generated by Django 5.1.7 on 2025-08-30 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_bookingimportlog_template"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="api_booking_externa_7b71f1_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="api_booking_check_i_5302b5_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="api_booking_source_856f40_idx",
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="booking",
            name="booked_on",
            field=models.DateTimeField(
                blank=True, help_text="When the booking was made", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="adults",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of adult guests"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="earnings_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Earnings from booking",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="earnings_currency",
            field=models.CharField(
                default="USD", help_text="Currency for earnings", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="external_code",
            field=models.CharField(
                blank=True,
                help_text="External confirmation code from booking platform",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="external_status",
            field=models.CharField(
                blank=True,
                help_text="Status from external booking platform",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="last_import_update",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time this booking was updated via import",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="listing_name",
            field=models.CharField(
                blank=True,
                help_text="Listing name from booking platform",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="property_label_raw",
            field=models.CharField(
                blank=True,
                help_text="Original property label from Excel",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="raw_row",
            field=models.JSONField(
                blank=True, help_text="Raw Excel row data for audit", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="same_day_flag",
            field=models.BooleanField(
                default=False, help_text="Flag for same day cleaning"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="same_day_note",
            field=models.TextField(blank=True, help_text="Same day cleaning notes"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Booking source (Airbnb, VRBO, Direct, etc.)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_logs",
                to="api.bookingimporttemplate",
            ),
        ),
        migrations.RemoveField(
            model_name="booking",
            name="imported_at",
        ),
    ]
