# Generated by Django 5.1.7 on 2025-08-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_checklisttemplate_history_generatedtask_history"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="import_file",
        ),
        migrations.AddField(
            model_name="bookingimportlog",
            name="import_file_hash",
            field=models.CharField(
                blank=True, help_text="SHA256 hash for deduplication", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="bookingimportlog",
            name="import_file_name",
            field=models.CharField(
                blank=True, help_text="Original filename", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="bookingimportlog",
            name="import_file_size",
            field=models.IntegerField(default=0, help_text="File size in bytes"),
        ),
    ]
