# Generated by Django 5.1.7 on 2025-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_remove_file_storage_from_import_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingimportlog",
            name="warnings_count",
            field=models.IntegerField(
                default=0, help_text="Number of warnings during import"
            ),
        ),
    ]
