# Generated by Django 5.1.7 on 2025-08-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_add_warnings_count_to_import_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingimportlog",
            name="skipped_rows",
            field=models.IntegerField(
                default=0, help_text="Number of rows skipped due to no changes"
            ),
        ),
        migrations.AlterField(
            model_name="bookingimporttemplate",
            name="property_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_templates",
                to="api.property",
            ),
        ),
    ]
