# Generated by Django 5.1.7 on 2025-08-31 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_add_early_return_rows_to_import_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="Row number in the Excel file"),
                ),
                (
                    "conflict_data",
                    models.JSONField(
                        help_text="JSON data of the conflicting booking from Excel"
                    ),
                ),
                (
                    "detected_changes",
                    models.JSONField(
                        default=dict,
                        help_text="JSON of detected changes between existing and new data",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("direct_owner", "Direct/Owner Booking"),
                            ("platform", "Platform Booking"),
                        ],
                        help_text="Type of conflict",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Resolution"),
                            ("resolved", "Resolved"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Resolution status",
                        max_length=20,
                    ),
                ),
                (
                    "resolution_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("update", "Update Existing Booking"),
                            ("create_new", "Create New Booking"),
                            ("skip", "Skip This Row"),
                        ],
                        help_text="Action taken to resolve conflict",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "existing_booking",
                    models.ForeignKey(
                        blank=True,
                        help_text="Existing booking that conflicts",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_conflicts",
                        to="api.booking",
                    ),
                ),
                (
                    "import_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="api.bookingimportlog",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("import_log", "row_number")},
            },
        ),
    ]
