# Generated by Django 5.1.7 on 2025-08-31 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_bookingimportlog_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookingimportlog",
            options={"ordering": ["-imported_at"]},
        ),
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="import_file_hash",
        ),
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="import_file_name",
        ),
        migrations.RemoveField(
            model_name="bookingimportlog",
            name="import_file_size",
        ),
        migrations.AddField(
            model_name="bookingimportlog",
            name="import_file",
            field=models.FileField(
                blank=True, null=True, upload_to="booking_imports/%Y/%m/"
            ),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="errors_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="errors_log",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="successful_imports",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bookingimportlog",
            name="total_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="BookingConflictSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Unique session identifier",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "import_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="booking_imports/conflicts/%Y/%m/",
                    ),
                ),
                ("total_conflicts", models.IntegerField(default=0)),
                ("resolved_conflicts", models.IntegerField(default=0)),
                (
                    "conflicts_data",
                    models.JSONField(
                        default=dict, help_text="Serialized conflict data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Session expiration time"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingConflictResolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("platform_update", "Platform Booking Update"),
                            ("direct_duplicate", "Direct Booking Duplicate"),
                            ("date_change", "Date Change Detected"),
                            ("guest_change", "Guest Information Change"),
                            ("property_change", "Property Change"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        help_text="Confidence that bookings are the same (0.0-1.0)"
                    ),
                ),
                (
                    "new_booking_data",
                    models.JSONField(help_text="Data from Excel import"),
                ),
                (
                    "detected_changes",
                    models.JSONField(help_text="Changes that would be applied"),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("update", "Update Existing Booking"),
                            ("create_new", "Create New Booking"),
                            ("skip", "Skip This Booking"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="User notes for this resolution"
                    ),
                ),
                (
                    "selected_changes",
                    models.JSONField(
                        default=list,
                        help_text="Which changes to apply (if update chosen)",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "existing_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict_resolutions",
                        to="api.booking",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conflict_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resolutions",
                        to="api.bookingconflictsession",
                    ),
                ),
            ],
            options={
                "ordering": ["confidence_score"],
            },
        ),
        migrations.DeleteModel(
            name="ConflictResolution",
        ),
    ]
