# Generated by Django 5.1.7 on 2025-08-31 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_bookingimportlog_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingconflictsession",
            name="created_by",
        ),
        migrations.AlterField(
            model_name="bookingimporttemplate",
            name="property_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="import_templates",
                to="api.property",
            ),
        ),
        migrations.DeleteModel(
            name="BookingConflictResolution",
        ),
        migrations.DeleteModel(
            name="BookingConflictSession",
        ),
    ]
