# Generated by Django 5.1.7 on 2025-09-02 05:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_add_uploaded_by_to_taskimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskimage",
            name="image",
            field=models.ImageField(upload_to=api.models.task_image_upload_path),
        ),
    ]
