# Generated by Django 5.1.7 on 2025-09-04 03:19

import api.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_update_taskimage_upload_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_via",
            field=models.CharField(
                default="manual",
                help_text="manual|excel_import|api|system",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="modified_via",
            field=models.CharField(
                default="manual",
                help_text="manual|excel_import|api|system",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_locked_by_user",
            field=models.BooleanField(
                default=False, help_text="Prevent auto-updates from imports"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="propertyinventory",
            name="current_stock",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="propertyinventory",
            name="max_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum stock capacity",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="propertyinventory",
            name="par_level",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Minimum stock level before reorder",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="scheduletemplate",
            name="time_of_day",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Default time for generated tasks",
            ),
        ),
        migrations.AlterField(
            model_name="taskimage",
            name="image",
            field=models.ImageField(
                upload_to=api.models.task_image_upload_path,
                validators=[api.models.validate_task_image],
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property", "check_in_date"],
                name="api_booking_propert_cf317d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["property", "check_out_date"],
                name="api_booking_propert_9bd0f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="api_booking_status_996dbb_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["source", "external_code"], name="api_booking_source_4e78fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["user"], name="api_device_user_id_ce916f_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read"], name="api_notific_recipie_4ac23c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["push_sent"], name="api_notific_push_se_631172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["timestamp"], name="api_notific_timesta_296212_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="property",
            index=models.Index(fields=["name"], name="api_propert_name_32b0c4_idx"),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.CheckConstraint(
                condition=models.Q(("check_in_date__lt", models.F("check_out_date"))),
                name="booking_checkin_before_checkout",
            ),
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_code__gt", "")),
                fields=("property", "source", "external_code"),
                name="uniq_booking_external_code_per_property_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="property",
            constraint=models.UniqueConstraint(
                fields=("name",), name="uniq_property_name"
            ),
        ),
    ]
