# Generated by Django 5.1.7 on 2025-09-05 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_add_audit_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="deletion_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="bookingimportlog",
            name="total_tasks_created",
            field=models.IntegerField(
                default=0, help_text="Number of automated tasks created"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="deletion_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="property",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="deletion_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="task",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="AutoTaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification", max_length=100
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this template is active"
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("inspection", "Inspection"),
                            ("preparation", "Preparation"),
                            ("other", "Other"),
                        ],
                        default="cleaning",
                        max_length=20,
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="Task title template. Use {property}, {guest_name}, {check_in_date}, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "description_template",
                    models.TextField(
                        blank=True,
                        help_text="Task description template. Use {property}, {guest_name}, {check_in_date}, etc.",
                    ),
                ),
                (
                    "timing_type",
                    models.CharField(
                        choices=[
                            ("before_checkin", "Days Before Check-in"),
                            ("after_checkout", "Days After Check-out"),
                            ("fixed_time", "Fixed Time of Day"),
                        ],
                        default="before_checkin",
                        max_length=20,
                    ),
                ),
                (
                    "timing_offset",
                    models.IntegerField(
                        default=1,
                        help_text="Days before/after check-in/out (positive number)",
                    ),
                ),
                (
                    "timing_hour",
                    models.TimeField(
                        blank=True,
                        help_text="Specific time of day (optional)",
                        null=True,
                    ),
                ),
                (
                    "booking_sources",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of booking sources (e.g., 'Airbnb,VRBO') or empty for all",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_task_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "default_assignee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default user to assign tasks to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property_types",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Apply only to specific properties (empty = all properties)",
                        to="api.property",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="created_by_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template that created this task (if auto-generated)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.autotasktemplate",
            ),
        ),
        migrations.CreateModel(
            name="TaskTemplateTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_info",
                        to="api.task",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.autotasktemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Template Tracking",
                "verbose_name_plural": "Task Template Tracking",
            },
        ),
    ]
