# Generated by Django 5.1.7 on 2025-09-05 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_add_task_types_alignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("created_by_template__isnull", False), ("is_deleted", False)
                ),
                fields=("booking", "created_by_template"),
                name="uniq_template_task_per_booking",
            ),
        ),
    ]
