# Generated by Django 5.1.10 on 2025-09-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_add_taskimage_metadata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="property",
            new_name="property_ref",
        ),
    ]
