# Generated by Django 5.1.10 on 2025-09-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_add_password_reset_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="can_view_other_teams",
            field=models.BooleanField(
                default=False,
                help_text="Can view other department dashboards (maintenance, cleaning, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="can_view_team_tasks",
            field=models.BooleanField(
                default=True,
                help_text="Can view all team tasks in department dashboards",
            ),
        ),
    ]
