# Generated by Django 5.1.10 on 2025-09-09 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_add_lost_found_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lostfounditem",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lostfound_modified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lostfounditem",
            name="modified_via",
            field=models.CharField(
                default="dashboard",
                help_text="admin|dashboard|api|system",
                max_length=32,
            ),
        ),
    ]
