# Generated by Django 5.1.10 on 2025-09-09 08:30

from django.db import migrations, connection


def create_btree_gist_extension(apps, schema_editor):
    """Create btree_gist extension only for PostgreSQL databases."""
    if connection.vendor == 'postgresql':
        try:
            schema_editor.execute("CREATE EXTENSION IF NOT EXISTS btree_gist;")
        except Exception as e:
            print(f"Warning: Could not create btree_gist extension: {e}")
            pass


def drop_btree_gist_extension(apps, schema_editor):
    """Drop btree_gist extension only for PostgreSQL databases."""
    if connection.vendor == 'postgresql':
        schema_editor.execute("DROP EXTENSION IF EXISTS btree_gist;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_add_lost_found_history"),
    ]

    operations = [
        migrations.RunPython(
            create_btree_gist_extension,
            reverse_code=drop_btree_gist_extension,
        ),
    ]


