# Generated by Django 5.1.10 on 2025-09-10 03:23

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.conf import settings
from django.db import migrations, models, connection


def add_booking_no_overlap_constraint(apps, schema_editor):
    if connection.vendor == 'postgresql':
        # Ensure idempotency: drop if exists first
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")
        Booking = apps.get_model('api', 'Booking')
        constraint = django.contrib.postgres.constraints.ExclusionConstraint(
            condition=models.Q(
                ("status__in", ["cancelled", "completed"]), _negated=True
            ),
            expressions=[
                (models.F("property"), "="),
                (
                    models.Func(
                        models.F("check_in_date"),
                        models.F("check_out_date"),
                        function="tstzrange",
                        output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                    ),
                    "&&",
                ),
            ],
            name="booking_no_overlap_active",
        )
        # Add the constraint directly
        schema_editor.add_constraint(Booking, constraint)


def remove_booking_no_overlap_constraint(apps, schema_editor):
    if connection.vendor == 'postgresql':
        # Remove safely
        schema_editor.execute("ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;")


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_booking_booking_no_overlap_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="task_group",
            field=models.CharField(
                choices=[
                    ("cleaning", "Cleaning"),
                    ("maintenance", "Maintenance"),
                    ("laundry", "Laundry"),
                    ("lawn_pool", "Lawn/Pool"),
                    ("general", "General"),
                    ("none", "Not Assigned"),
                ],
                default="none",
                help_text="Primary task group for staff assignment and dashboard permissions",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            add_booking_no_overlap_constraint,
            reverse_code=remove_booking_no_overlap_constraint,
        ),
    ]
