# Generated by Django 5.1.12 on 2025-09-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_add_task_group_to_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taskimage",
            options={
                "ordering": ["task", "photo_type", "sequence_number", "uploaded_at"]
            },
        ),
        migrations.AddField(
            model_name="taskimage",
            name="description",
            field=models.TextField(
                blank=True, help_text="Detailed description of what the photo shows"
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Primary photo for this type (e.g., main 'before' photo)",
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="photo_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("archived", "Archived"),
                ],
                default="pending",
                help_text="Approval status of the photo",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="photo_type",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("after", "After"),
                    ("during", "During"),
                    ("reference", "Reference"),
                    ("damage", "Damage"),
                    ("general", "General"),
                ],
                default="general",
                help_text="Type of photo for before/after comparison",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="taskimage",
            name="sequence_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Order within the same photo_type group"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskimage",
            unique_together={("task", "photo_type", "sequence_number")},
        ),
        migrations.AddIndex(
            model_name="taskimage",
            index=models.Index(
                fields=["task", "photo_type"], name="api_taskima_task_id_5e0a0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskimage",
            index=models.Index(
                fields=["photo_status"], name="api_taskima_photo_s_0e2a06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskimage",
            index=models.Index(
                fields=["uploaded_at"], name="api_taskima_uploade_bbdd21_idx"
            ),
        ),
    ]