# Generated by Django 5.1.12 on 2025-09-11 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0069_booking_booking_no_overlap_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=32, unique=True)),
                (
                    "task_group",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("maintenance", "Maintenance"),
                            ("laundry", "Laundry"),
                            ("lawn_pool", "Lawn/Pool"),
                            ("general", "General"),
                            ("none", "Not Assigned"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times this code can be used (0 = unlimited)",
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Leave blank for no expiration", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this invite code"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "used_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="used_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
