# Generated by Django 5.1.12 on 2025-09-15 19:10

from django.db import migrations, connection


def ensure_postgresql_extensions(apps, schema_editor):
    """
    Ensure PostgreSQL extensions are available for CI compatibility.
    This migration is designed to be robust and not fail if extensions can't be created.
    """
    if connection.vendor != 'postgresql':
        return

    # List of extensions we need
    extensions = [
        'btree_gist',
    ]
    
    for extension in extensions:
        try:
            schema_editor.execute(f"CREATE EXTENSION IF NOT EXISTS {extension};")
            print(f"✅ Successfully ensured {extension} extension is available")
        except Exception as e:
            print(f"⚠️  Warning: Could not create {extension} extension: {e}")
            # Continue with other extensions even if one fails
            continue


def noop_reverse(apps, schema_editor):
    """No-op reverse migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_fix_invite_code_usage_tracking"),
    ]

    operations = [
        migrations.RunPython(
            ensure_postgresql_extensions,
            reverse_code=noop_reverse,
        ),
    ]
