# Generated by Django 5.1.12 on 2025-10-19 05:28

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0077_taskimage_checklist_response_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File Attachment"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Message text content")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                ("attachment_name", models.CharField(blank=True, max_length=255)),
                (
                    "attachment_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "read_by",
                    models.JSONField(
                        default=dict,
                        help_text="User IDs and timestamps who have read this message",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_read_at", models.DateTimeField(blank=True, null=True)),
                ("muted", models.BooleanField(default=False)),
                ("muted_until", models.DateTimeField(blank=True, null=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Display name for group chats",
                        max_length=255,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Message"),
                            ("group", "Group Chat"),
                            ("task", "Task Discussion"),
                            ("property", "Property Discussion"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-modified_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatTypingIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("assigned", "Assigned"),
                    ("unassigned", "Unassigned"),
                    ("status_changed", "Status changed"),
                    ("due_date_changed", "Due date changed"),
                    ("title_changed", "Title changed"),
                    ("description_changed", "Description changed"),
                    ("photo_added", "Photo added"),
                    ("photo_deleted", "Photo deleted"),
                    ("photo_approved", "Photo approved"),
                    ("photo_rejected", "Photo rejected"),
                    ("created", "Task created"),
                ],
                default="status_changed",
                max_length=32,
            ),
        ),
        # Booking overlap constraint already exists in previous migration 0077
        # Removed to prevent duplicate constraint error
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="api.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="property",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="api.property",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_rooms",
                to="api.task",
            ),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="api.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="api.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chattypingindicator",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_users",
                to="api.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chattypingindicator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "is_active"], name="api_chatroo_room_ty_edc8c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(fields=["task"], name="api_chatroo_task_id_53679a_idx"),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["property"], name="api_chatroo_propert_99726f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["modified_at"], name="api_chatroo_modifie_eebf6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["user", "room"], name="api_chatpar_user_id_ae127e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatparticipant",
            index=models.Index(
                fields=["last_read_at"], name="api_chatpar_last_re_495a34_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("room", "user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "-created_at"], name="api_chatmes_room_id_c47c7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender"], name="api_chatmes_sender__7c187d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["is_deleted", "-created_at"],
                name="api_chatmes_is_dele_30ea72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chattypingindicator",
            index=models.Index(
                fields=["room", "started_at"], name="api_chattyp_room_id_e4c8eb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chattypingindicator",
            unique_together={("room", "user")},
        ),
    ]
