# Generated by Django 5.1.15 on 2025-12-30 04:47

from django.db import migrations, connection


def ensure_booking_overlap_constraint(apps, schema_editor):
    """
    Ensure the booking_no_overlap_active exclusion constraint exists.
    Uses raw SQL to be idempotent - removes and recreates if needed.
    """
    if connection.vendor != 'postgresql':
        return

    # Drop constraint if it exists (from any previous migration)
    try:
        schema_editor.execute(
            "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
        )
    except Exception:
        pass

    # Create the constraint with correct definition
    try:
        schema_editor.execute(
            """
            ALTER TABLE api_booking
            ADD CONSTRAINT booking_no_overlap_active
            EXCLUDE USING gist (
                property_id WITH =,
                tstzrange(check_in_date, check_out_date) WITH &&
            ) WHERE (status NOT IN ('cancelled', 'completed'));
            """
        )
    except Exception as e:
        print(f"Warning: Could not create booking overlap constraint: {e}")


def drop_booking_overlap_constraint(apps, schema_editor):
    """Reverse operation - drop the constraint."""
    if connection.vendor == 'postgresql':
        schema_editor.execute(
            "ALTER TABLE api_booking DROP CONSTRAINT IF EXISTS booking_no_overlap_active;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_chatmessage_chatparticipant_chatroom_and_more"),
    ]

    operations = [
        migrations.RunPython(
            ensure_booking_overlap_constraint,
            reverse_code=drop_booking_overlap_constraint,
        ),
    ]
