// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPVfZGxRiNZcMFaTcVP6F42JSfRh3gtQ',
    appId: '1:676131410875:web:529b65628a66239b2bea9e',
    messagingSenderId: '676131410875',
    projectId: 'aristayapp',
    authDomain: 'aristayapp.firebaseapp.com',
    storageBucket: 'aristayapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYS2OX0zBeSjBmjm3F0NOR8kxvMTlIweM',
    appId: '1:676131410875:android:d7ba332bda9d44022bea9e',
    messagingSenderId: '676131410875',
    projectId: 'aristayapp',
    storageBucket: 'aristayapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEWjPyKBSb3TISbeLXposnwGZLb89KsoY',
    appId: '1:676131410875:ios:368ac79a81d4c17b2bea9e',
    messagingSenderId: '676131410875',
    projectId: 'aristayapp',
    storageBucket: 'aristayapp.firebasestorage.app',
    iosBundleId: 'com.cosmomgmt.app',
  );
}
